# Assignment 1 

In [2]:
# 1)Import the Numpy package under the name np

import numpy as np

In [2]:
## 2)Create a null vector of size 10

x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [3]:
## 3)Create a null vector of size 10 but the fifth value which is 1

x[4]=1
print(x)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [4]:
## 4)Create a vector with values ranging from 10 to 49

vec=np.arange(10,50)
print(vec)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [5]:
## 5)Reverse a vector (the first element becomes last)

rev=np.flip(vec)
print(rev)


[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


In [6]:
## 6)Create a 3x3 matrix with values ranging from 0 to 8

np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [5]:
## 7)Find indices of non­zero elements from [1,2,0,0,4,0]

arr=[1,2,0,0,4,0]
np.nonzero(arr)

(array([0, 1, 4], dtype=int64),)

In [7]:
## 8)Create a 3x3x3 array with random values

np.random.random((3,3,3))

array([[[0.79051461, 0.44624775, 0.60333989],
        [0.32165979, 0.23583453, 0.74175578],
        [0.57985347, 0.57713423, 0.40036407]],

       [[0.66623162, 0.63807613, 0.92298881],
        [0.65840579, 0.19090695, 0.85732251],
        [0.22845305, 0.86042848, 0.64467011]],

       [[0.61923576, 0.10473675, 0.75467649],
        [0.3157409 , 0.18719277, 0.78462345],
        [0.53080401, 0.2904856 , 0.58769958]]])

In [8]:
## 9)Create a random vector of size 30 and find the mean value

x=np.random.random(30)
mean=x.mean()
print(mean)

0.42186283406707487


In [9]:
## 10)Create a 2d array with 1 on the border and 0 inside

x=np.ones((4,5))
x[1:-1,1:-1] = 0
print(x)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [27]:
## 11)Create an 8x8 matrix and fill it with a checkerboard pattern

Z=np.zeros((8,8), dtype=int)
Z[1::2, ::2]=1
Z[::2, 1::2]=1
print (Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [10]:
## 12)What is the major difference between sets, lists, tuples and dictionaries?

# List is a non-homogeneous data structure which stores the elements in single row and multiple rows and columns
# List allows duplicate elements. List is enclosed in []. List are mutable.

# Tuple is also a non-homogeneous data structure which stores single row and multiple rows and columns.
# Tuple allows duplicate elements. It is enclosed in (). Tuples are immutable.

# Set data structure is also non-homogeneous data structure but stores in single row.
# Set will not allow duplicate elements. Set is enclosed by {}. SETS are unordered while other are orderd.

# Dictionary is also a non-homogeneous data structure which stores key value pairs, in which the key cannot be dublicated.
# Dictionary is enclosed by {}.

In [31]:
## 13)Print first 10 natural numbers using while loop.

i=1
while ( i <= 10):
    print (i, end = ' ')
    i= i+1

1 2 3 4 5 6 7 8 9 10 

In [29]:
## 14)Print the numbers -10 to -1 using for loop.

for i in range(-10,0):
    print(i, end=" ")


-10 -9 -8 -7 -6 -5 -4 -3 -2 -1 

In [13]:
## 15)Print the message “Done” after successful execution of any for a loop. 

for i in range(1,11):
    prod=67*i
    print(67,"*",i,"=",prod)
print("Done")

67 * 1 = 67
67 * 2 = 134
67 * 3 = 201
67 * 4 = 268
67 * 5 = 335
67 * 6 = 402
67 * 7 = 469
67 * 8 = 536
67 * 9 = 603
67 * 10 = 670
Done


In [25]:
## 16)Create a random vector of size 10 and sort it.

Z=np.random.random(10)
print(Z)
Z.sort()
print("\n",Z)


[0.53117722 0.53856769 0.35952555 0.25835318 0.21517094 0.02132967
 0.75312526 0.7541529  0.72675722 0.27505272]

 [0.02132967 0.21517094 0.25835318 0.27505272 0.35952555 0.53117722
 0.53856769 0.72675722 0.75312526 0.7541529 ]


In [15]:
## 17)Execute any three math functions using NumPy.

import math
print(math.remainder(47,9))

print(math.factorial(4))

r=6
area=math.pi*6*6
print(area)


2.0
24
113.09733552923255
